# Base configs
baseurl: ""
url: "https://bibi-photography.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Bibi Photography"
subtitle: "Professional photographer in Sarasota, Florida"
author: "Bogdana Burlacu"
bio: "I'm a professional photographer from Sarasota, Florida. I cover weddings, family and corporate events, and real-estate photography all around the Suncoast. Contact me to discuss your next project!"
publicise: ""
web_design: "JV"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
  
